### ISSUE TITLE
GraphQL 插件实际上没有获取到请求参数

### ISSUE THREAD

**Issue by lagnx** [opensolon/solon-integration#3]
运行测试代码 `solon-integration-projects/solon-plugin/graphql-solon-plugin/src/test/java/graphql/solon/test/QueryTest.java` 

![image](https://github.com/noear/solon-integration/assets/61501001/b2fbdca7-fa81-4d46-a3d3-8a28c65fa73d)

会发现入参 ID 实际上没有获取到，为 null

![image](https://github.com/noear/solon-integration/assets/61501001/3787f18b-95fe-49df-b957-3ed1107a14d3)

**Comment by lagnx** [comment]
入参可能忘了组装，如下代码加一行就行了
![image](https://github.com/noear/solon-integration/assets/61501001/68135fc4-2285-405c-b379-2bd02b6ebc89)

**Comment by lagnx** [comment]
是否需要提个PR？

**Comment by noear** [comment]
@lagnx 要的，提交个 pr :)。。。另外，帮忙多加些单测：）

**Comment by noear** [comment]
测试相关的目录命名，看下：

https://github.com/noear/solon-integration/blob/main/CONTRIBUTING.md

**Comment by lagnx** [comment]
OK

**Comment by lagnx** [comment]
尝试测试 Mutation 时，发现对象类型的参数无法正常解析，json参数解析后得到的是 LinkedHashMap，反射调用会出现 IllegalArgumentException 的异常

关键测试代码：
```java
    @QueryMapping(typeName = "Mutation")
    public BookInputDTO createBook(@Param BookInputDTO book) {
        return book;
    }
```

是我 @QueryMapping 使用错误了？怀疑是代码没有写相关的 Loader 或者 Fetcher ？看到 BatchMapping 可以正常解析如 `List<Course> courses` 类型的入参

**Comment by lagnx** [comment]
我找到问题了，在 ArgumentMethodArgumentResolver 中解析的问题，测试用例和 bug 修复了一起提

**Comment by lagnx** [comment]
修改和删除测试用例写完了，使用文档按照我自己的理解写完了（可能需要校对），但是订阅的测试用例不大会写，GraphQL 执行 subscription 似乎需要 websocket 连接发送请求，我尝试了一下但是不清楚哪里出了问题（`app.enableWebSocket(true)` 已经设置）

```java
@Test
public void testSubscription() throws IOException, InterruptedException {
    ProductPriceHistoryDTO product = new ProductPriceHistoryDTO(123L, new Date(), 999);

    ONode param = new ONode();
    ONode variables = new ONode();
    variables.set("productId", product.getId());
    param.set("query",
            ResourceUtil.getResourceAsString("/query/subscriptionProduct.gqls"));
    param.set("variables", variables);
    param.set("operationName", "testSubscription");
    String json = param.toJson();

    // socket
    SimpleWebSocketClient client = new SimpleWebSocketClient("ws://127.0.0.1:8081/graphql") {
        @Override
        public void onMessage(String message) {
            super.onMessage(message);
            System.out.println("get a message: " + message);
        }
    };

    client.connectBlocking(10, TimeUnit.SECONDS);
    //定制心跳（可选）
    //client.heartbeatHandler(new HeartbeatHandlerDefault());
    //开始心跳 + 心跳时自动重连
    client.heartbeat(20_000, true);

    //发送测试
    client.send(json);

    //休息会儿
    for(int i = 0; i < 100; i++) {
        Thread.sleep(1000);
        System.out.println("====");
    }

    //关闭（使用 release 会同时停止心跳及自动重连）
    client.release();
}

```
subscriptionProduct.gqls 
```
subscription testSubscription($productId: ID!){
  notifyProductPriceChange(productId: $productId) {
    price
  }
}
```

**Comment by noear** [comment]
那订阅就先不搞：）

**Comment by fuzi1996** [comment]
> 修改和删除测试用例写完了，使用文档按照我自己的理解写完了（可能需要校对），但是订阅的测试用例不大会写，GraphQL 执行 subscription 似乎需要 websocket 连接发送请求，我尝试了一下但是不清楚哪里出了问题（`app.enableWebSocket(true)` 已经设置）
> 
> ```java
> @Test
> public void testSubscription() throws IOException, InterruptedException {
>     ProductPriceHistoryDTO product = new ProductPriceHistoryDTO(123L, new Date(), 999);
> 
>     ONode param = new ONode();
>     ONode variables = new ONode();
>     variables.set("productId", product.getId());
>     param.set("query",
>             ResourceUtil.getResourceAsString("/query/subscriptionProduct.gqls"));
>     param.set("variables", variables);
>     param.set("operationName", "testSubscription");
>     String json = param.toJson();
> 
>     // socket
>     SimpleWebSocketClient client = new SimpleWebSocketClient("ws://127.0.0.1:8081/graphql") {
>         @Override
>         public void onMessage(String message) {
>             super.onMessage(message);
>             System.out.println("get a message: " + message);
>         }
>     };
> 
>     client.connectBlocking(10, TimeUnit.SECONDS);
>     //定制心跳（可选）
>     //client.heartbeatHandler(new HeartbeatHandlerDefault());
>     //开始心跳 + 心跳时自动重连
>     client.heartbeat(20_000, true);
> 
>     //发送测试
>     client.send(json);
> 
>     //休息会儿
>     for(int i = 0; i < 100; i++) {
>         Thread.sleep(1000);
>         System.out.println("====");
>     }
> 
>     //关闭（使用 release 会同时停止心跳及自动重连）
>     client.release();
> }
> ```
> 
> subscriptionProduct.gqls
> 
> ```
> subscription testSubscription($productId: ID!){
>   notifyProductPriceChange(productId: $productId) {
>     price
>   }
> }
> ```

订阅有自己的协议，不是单纯的发送websocket信息，协议地址[https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md)

**Comment by noear** [comment]
是的。应该有自己专门的客户端发送。。。而且估计有子协议校验
