### ISSUE TITLE
添加支持tkMybatis的插件支持

### ISSUE THREAD

**Issue by tri5m** [opensolon/solon-integration#5]
tkMybatis是比较常用的mybatis增强工具，在部分头部公司内部用的比较多.
主打轻量级，对业务代码无侵入，兼容jpa注解等特性广受好评。
现将tkMybatis加入solon插件，以便于开发人员方便使用，完善solon生态。
项目地址： https://github.com/abel533/Mapper，
现接入4.x分支版本。

**Comment by noear** [comment]
建议在这个仓库： https://github.com/abel533/Mapper 下面，添加 "solon-plugin" 目录，然后在下面添加模块 “mapper-solon-plugin” 模块。。。并 pr 到到这个仓库。。。这样更有利于 solon 生态的发展（需要散出去）

**Comment by noear** [comment]
关于数据源的使用，最好保持这个概念： https://solon.noear.org/article/353

**Comment by noear** [comment]
这是 mybatis-solon-plugin 的使用说明： https://solon.noear.org/article/20

**Comment by tri5m** [comment]
插件已经开发完成，测试阶段，明天我试试Mapper作者加不加目录，应该可能性不大，因为这个版本已经基本完善，听说近期不会再发布新的版本了，下一个版本可能直接最少支持jdk17+SpringBoot3。

**Comment by noear** [comment]
你可以跟他先交流下：）多引导

**Comment by tri5m** [comment]
了然

**Comment by noear** [comment]
争取拿下：）。。。生态的重点，就是外散出去，不断有生态伙伴：）
